### ISSUE TITLE
trouble with sidguesser

### ISSUE THREAD

**Issue by marcelosoyyo** [quentinhardy/odat#17]
Hi, i've testing the standalone version in Oracle Linux 6 64bit, with oracle 12c, 1 cdb called cdb1 with 2 pdbs, pdb1_1 and pdb2_1

if i try:
./odat-libc2.5-x86_64 sidguesser -s ol6 -p 1521 --sids-min-size 6 --sids-max-size 6 --sid-charset bdp12_

it only detects sids cdb1 (as i have already added it to sids.txt) and pdb1_2 but not pdb1_1
if i try:
./odat-libc2.5-x86_64 sidguesser -s ol6 -p 1521 --sids-min-size 6 --sids-max-size 6 --sid-charset bdp112_
it detects cdb1 (as i have already added it to sids.txt) and both pdb1_1 & pdb1_2

so it seems its not trying to repeat characters from the charset.

**Comment by omair2084** [comment]
Good catch, this tool is using permutations 
`for aSID in permutations(list(charset), size):`
This should be replaced by **_product_** as seen in itertools example
```
product('ABCD', repeat=2)
AA AB AC AD BA BB BC BD CA CB CC CD DA DB DC DD
permutations('ABCD', 2)
AB AC AD BA BC BD CA CB CD DA DB DC
```

**Comment by quentinhardy** [comment]
Thank you for this bug fix.
Best regards.
