### ISSUE TITLE
How to use the standalone .tar.gz

### ISSUE THREAD

**Issue by fede333lago** [quentinhardy/odat#25]
Hi, sorry for the beginner question but how should i use the standalone installers? All I see is the zip files with the source code or the .tar.gz that has all the libraries. Should I compile something or am I missing the standalone executable somewhere?

Thanks!

**Comment by fede333lago** [comment]
Nevermind, I just saw the standalone between all the libraries. Sorry for the trouble.

**Comment by vulntor** [comment]
I wonder how to use the standalone too...not good at linux dev

**Comment by fede333lago** [comment]
I don't know if you're still having this issue, but the binary is inside the tar.gz, called "odat-libc2.5-x86_64"
