### ISSUE TITLE
tested on Oracle(11g XE) with module utlhttp error

### ISSUE THREAD

**Issue by byr0nchan** [quentinhardy/odat#26]
I have tested on Oracle(11g XE) with module utlhttp:

[root@root odat]# ./odat.py utlhttp -s 10.10.10.200 -d xe -U system -P oracle --send 115.239.211.112 80 temp.txt
22:43:57 WARNING -: Impossible to set the timeout value: ORA-06550: line 1, column 7: PLS-00201: identifier 'UTL_HTTP' must be declared ORA-06550: line 1, column 7: PL/SQL: Statement ignored

[1] (10.10.200.231:1521): Send the HTTP request stored in the temp.txt file
[-] Impossible to send the request: ORA-06550: line 1, column 13: PLS-00201: identifier 'UTL_HTTP' must be declared ORA-06550: line 1, column 13: PL/SQL: Item ignored ORA-06550: line 1, column 31: PLS-00201: identifier 'UTL_HTTP' must be declared ORA-06550: line 1, column 31: PL/SQL: Item ignored ORA-06550: line 1, column 75: PLS-00320: the declaration of the type of this expression is incomplete or malformed ORA-06550: line 1, column 75: PL/SQL: Statement ignored ORA-06550: line 1, column 155: PLS-00320: the declaration of the type of this expression is incomplete or malformed ORA-06550: line 1, column 155: PL/SQL: Statement ignored ORA-06550: line 1, column 220: PLS-00320: the declaration of the type of this expression is incomplete or malformed ORA-06550: line 1, column 201: PL/SQL: Statement ignored ORA-06550: line 1, column 296: PLS-00320: the declaration of the type of this expression is incomplete or malformed ORA-06550: line 1, column 274: PL/SQL: Statement ignored ORA-06550: line 1, column 317: PLS-00201: identifier 'UTL_HTTP' must be declared ORA-06550: line 1, column 190: PL/SQL: Statement ignored

**Comment by quentinhardy** [comment]
It seems UTL_HTTP package is not installed. See your message:
```
[...]identifier 'UTL_HTTP' must be declared[...]
```
Consequently, this error in log output is normal. 
You can't use the _utlhttp_ odat module.
