### ISSUE TITLE
test module "all"  cannot skip a module and continue to the next

### ISSUE THREAD

**Issue by byr0nchan** [quentinhardy/odat#27]
The login ADAMS has already been tested at least once. What do you want to do:
- stop (s/S)
- continue and ask every time (a/A)
- continue without to ask (c/C)
someone module maybe not use,i want skip to the next

**Comment by quentinhardy** [comment]
In this exact case, I assume you have already found valid credentials and you want to skip the research of new passwords. You can use the **-U** and **-P** for skipping this step with the _all_ module for example.

**Comment by quentinhardy** [comment]
Implemented in https://github.com/quentinhardy/odat/commit/9cfbdec1616b7796056890888e6eb806b2f33959
Thank you for the idea.

**Comment by mahmoudawni88** [comment]
Hi,

-U or -P isn't working.

**Comment by mahmoudawni88** [comment]
form the code, you have to reply with a 0r A, c or C, p or P

if rep == 's' or rep == 'S' : return 0
			elif rep == 'a' or rep == 'A' : return 1
			elif rep == 'c' or rep == 'C' : return 2
			elif rep == 'p' or rep == 'P': return 3
			
Thanks,
awni
