### ISSUE TITLE
Detect new version Oracle (18 and later)

### ISSUE THREAD

**Issue by zw0nner** [quentinhardy/odat#32]
My code for versions 18 and later:
if len(hexVsnnum) == 7:
    hexVersionList = struct.unpack('cc2sc2s',hexVsnnum)
elif len(hexVsnnum) == 8:
    hexVersionList = struct.unpack('2sc2sc2s',hexVsnnum)

**Comment by quentinhardy** [comment]
Thank you. 
I have done some modifications and ODAT is now compatible with Oracle Database 18c.
