### ISSUE TITLE
Should switch to Python 3

### ISSUE THREAD

**Issue by sbrun** [quentinhardy/odat#33]
Python 2.x will no longer be supported by their upstream developers in 2020. Thus Debian developers are actively removing Python 2 support in Debian Testing with the goal of getting rid of Python 2 in Debian 11 (bullseye).
Kali is tracking Debian Testing and is thus affected by this. You should consider to switch odat to Python 3.

FWIW this is tracked in https://gitlab.com/kalilinux/packages/odat/issues/1 on the Kali side.

**Comment by quentinhardy** [comment]
I know, I will migrate the code to python 3 when I will have a moment.

**Comment by FirefighterBlu3** [comment]
I work for a company that runs and parses the output of odat for customers. We very much prefer to use modern Python, so I'm happy to help with this

**Comment by quentinhardy** [comment]
Can you try https://github.com/quentinhardy/odat/tree/master-python3 and https://github.com/quentinhardy/odat/releases/tag/4.0 ?

This is the version 4 of ODAT. It is compatible with python 3. No new feature in this version, just compatible with python 3 now.

**Comment by sbrun** [comment]
Hello,
I'm sorry I didn't see your comment on october 5th.
https://github.com/quentinhardy/odat/tree/master-python3 : I just packaged it for kali. I didn't see issue with Python 3.

FYI: I first tested the 4.0.tar.gz from https://github.com/quentinhardy/odat/releases/tag/4.0
It's only python2 compatible.
Thank you very much for the update.
