### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by ghost** [quentinhardy/odat#43]
/opt/odat/odat.py:52: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp

**Comment by quentinhardy** [comment]
**imp** module is not required in odat. I have removed it from odat.
It is done in https://github.com/quentinhardy/odat/commit/1a792751247bb830f5d7d8b4e7a67f582723914b

Thank you,
