### ISSUE TITLE
Issue with passwordguesser module

### ISSUE THREAD

**Issue by aniyazov25** [quentinhardy/odat#45]
> Traceback (most recent call last):
>   File "odat.py", line 569, in <module>
>     main()
>   File "odat.py", line 564, in main
>     arguments.func(args)
>   File "/opt/odat/PasswordGuesser.py", line 185, in runPasswordGuesserModule
>     passwordGuesser.searchValideAccounts()
>   File "/opt/odat/PasswordGuesser.py", line 98, in searchValideAccounts
>     pbar,nb = self.getStandardBarStarted(len(self.accounts)), 0
>   File "/opt/odat/OracleDatabase.py", line 327, in getStandardBarStarted
>     return ProgressBar(widgets=['', Percentage(), ' ', Bar(),' ', ETA(), ' ',''], maxval=maxvalue).start()
>   File "/opt/odat/progressbar.py", line 213, in __init__
>     assert (maxval > 0),'maxval <= 0' 
> AssertionError: maxval <= 0

This error comes up when trying to use my own user/pass list. 

I uninstalled and reinstalled a few times, following the install instructions to the dot.

Any advice on what to do will be helpful. Thank you

**Comment by engdan** [comment]
I am also experiencing this issue, both when trying to use my own list but also when trying to use accounts/pwd.txt when I've specified a username (to bruteforce for a single username)

**Comment by quentinhardy** [comment]
@aniyazov25
The default separator is "/" between login and password.
If you don't use this separator, no credentials will be loaded in odat and you will have the error : "AssertionError: maxval <= 0"
See accounts/accounts_multiple.txt file for an example

**Comment by quentinhardy** [comment]
@engdan 
Can you check your separator in account file? I think you have the same problen than @aniyazov25.
See accounts/accounts_multiple.txt file for an example.

This following option has to be used for a login file and a password file:
```bash
--accounts-files accounts/logins.txt accounts/pwds.txt
```
See logins.txt and pwds.txt for examples.

**Comment by quentinhardy** [comment]
Catch this error, see https://github.com/quentinhardy/odat/commit/46d0a085454970b99ac3448656ecc3dc465e6cf0 for details.

New argument: '--separator' if you want use another separator than '/', see https://github.com/quentinhardy/odat/commit/3c76e96970ded6fd8e10ba55eabc48fa58d8b139
