### ISSUE TITLE
error while running the module

### ISSUE THREAD

**Issue by stack00** [quentinhardy/odat#47]
Hi, the tool was working fine until today I got this error message, I have followed all the instructions and installed all that requires for tool to work, need help in this please
root@kali:/opt/odat# ./odat.py
WARNING:root:You need to install python scapy if you want to use the CVE_2012_3137 module !
Traceback (most recent call last):
  File "./odat.py", line 46, in <module>
    from CVE_XXXX_YYYY import CVE_XXXX_YYYY, runCVEXXXYYYModule
  File "/opt/odat/CVE_XXXX_YYYY.py", line 5, in <module>
    from passlib.hash import oracle11 as oracle11
ImportError: No module named passlib.hash

**Comment by quentinhardy** [comment]
Do you have tried ```sudo pip3 install passlib``` (with pip on python 3 version)?
