### ISSUE TITLE
Little typo when no accounts where found

### ISSUE THREAD

**Issue by Keldorb** [quentinhardy/odat#48]
In the error message to enumerate users / password the "not found message is"

[-] No found a valid account on <ip>/<database>. You should try with the option '--accounts-file accounts/accounts_multiple.txt' or '--accounts-file accounts/logins.txt accounts/pwds.txt'

For the username and password combo it states in the message  "--accounts-file...." instead of "--accounts-files...."
I would ove to create a pull request but dont have the time right now. 
Sorry if this is not the right way to report this.

**Comment by quentinhardy** [comment]
Fixed in https://github.com/quentinhardy/odat/commit/c0c43649d73b145a206f80ab3119e55a6d51f405
Thank you.
