### ISSUE TITLE
odat does not start

### ISSUE THREAD

**Issue by kastahl** [quentinhardy/odat#53]
I installed odat with all dependencies as directed.

When I try to start odat.py nothing happens, no errors as well as no feedback.
I used oracle version 21 and also tried version 19.9. Same issue on both.

`# python3 odat.py -h`

Any ideas what could be wrong?

**Comment by 0xPanic** [comment]
I have the same issue but was able to resolve it by using the latest standalone release

**Comment by koutto** [comment]
Hey guys, why are you not using the release version of odat ? Working without any problem on latest kali without having nothing to do

**Comment by quentinhardy** [comment]
Hello,
@kastahl, do you have found the problem ?

**Comment by beanking** [comment]
Having the same issue with Oracle 21

**Comment by vinaynair95** [comment]
Hey, 
Below commands worked for me (After installing all the dependencies) (I downloaded oracle version 19.10)
1. apt-get install -y libaio1 python-dev alien python3-pip python3-scapy
2. pip3 install cx_Oracle (The blog says that this cmd (python -c 'import cx_Oracle') shouldnt return any error.. it returned an error to me so you may ignore it
3. pip install colorlog termcolor pycrypto passlib argcomplete

run cmd: python3 odat.py -h
reference: https://dastinia.io/tutorial/2018/07/31/installing-oracle-database-attacking-tool-on-kali/

**Comment by quentinhardy** [comment]
@beanking, @0xPanic and @kastah What are your OS ? Kali ?
