### ISSUE TITLE
Adding 'orclcdb' to SID list

### ISSUE THREAD

**Issue by qgrosperrin** [quentinhardy/odat#59]
Hi, 

Thanks for the tool.
Just thought it could be worth adding 'orclcdb' to the list of SIDs. It's been a few times I have seen it used, especially in default Oracle dev setup, but it's not included in the list.

**Comment by quentinhardy** [comment]
thank you

**Comment by quentinhardy** [comment]
See https://github.com/quentinhardy/odat/commit/24af4da8d50a55c05379dd495e8489dbd7573b5c
