### ISSUE TITLE
pycrypto dosent work anymore

### ISSUE THREAD

**Issue by MaximusKI** [quentinhardy/odat#66]
haved troubles installing the requirement i installed pycryptodome instead and worked fine

**Comment by unixerius** [comment]
Simply installing _python3-pycryptodome_ didn't do it for me.

Running ODAT breaks on CVE_2012_3137.py, which does a `from Crypto.Cipher import AES`. This should work, based on this -> https://www.pycryptodome.org/src/examples#encrypt-data-with-aes

Interestingly, it doesn't.

After changing the import statement to `from Cryptodome.Cipher import AES`, ODAT seems to run better.
