### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Cricco95** [quentinhardy/odat#9]
Nice tool. The only thing to do at the moment it's to update Oracle Instant Client libraries to version 12.1.0.2.0 and create a 64bit version of the tool. Thank you for your work!

**Comment by quentinhardy** [comment]
The standalone client is not up-to-date. I will generate a new standalone client as soon as possible.

**Comment by quentinhardy** [comment]
I will generate a new standalone in few weeks/month. I'm working on a new version (2.0) and I don't have lot of time to generate a new standalone after each commit. The source version must be used while a new standalone is not created.
